from binance_common.configuration import ConfigurationWebSocketStreams
from binance_common.constants import DERIVATIVES_TRADING_OPTIONS_WS_STREAMS_PROD_URL
from binance_sdk_derivatives_trading_options.derivatives_trading_options import DerivativesTradingOptions


configuration_ws_streams = ConfigurationWebSocketStreams(
    stream_url=DERIVATIVES_TRADING_OPTIONS_WS_STREAMS_PROD_URL,
)

client = DerivativesTradingOptions(config_ws_streams=configuration_ws_streams)

